// filepath: /home/diego/Documentos/GitHub/stockunlimited/src/app/layout.tsx
import type { Metadata } from "next";
import "../globals.css";
import Sidebar from "@/components/Sidebar";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div
      className="dashboard-layout"
      style={{ display: "flex", height: "100vh" }}
    >
      <Sidebar />
      <main className="content" style={{ flex: 1, overflowY: "auto" }}>
        {children}
      </main>
    </div>
  );
}
