// filepath: /home/diego/Documentos/GitHub/stockunlimited/src/app/layout.tsx
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import Navbar from "../../components/Navbar"; // Importa el componente de barra de navegación
import Sidebar from "@/components/Sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navbar /> 
        <div className="dashboard-layout" style={{ display: 'flex', height: '100vh' }}>
            <Sidebar />
            <main className="content" style={{ flex: 1, overflowY: 'auto' }}>
                {children}
            </main>
        </div>
        
      </body>
    </html>
  );
}